package raf.graffito.dsw.message;

public enum EventType {
    ERROR,
    WORKSPACE_CANNOT_BE_DELETED,
    NODE_CANNOT_BE_DELETED,
    CANNOT_ADD_CHILD,
    CANNOT_DELETE_FILE,
    NODE_ALREADY_EXISTS,
    WARNING,
    NODE_NOT_SELECTED,
    COMPONENT_NOT_SELECTED,
    NOTIFICATION,
    NAME_CANNOT_BE_EMPTY,
    MUST_INSERT_NAME,
    RESOURCE_NOT_FOUND,
    PROJECT_MUST_HAVE_PRESENTATION_OR_SLIDE,
    SLIDE_CANNOT_CONTAIN_CHILDREN,
    PRESENTATION_CAN_ONLY_CONTAIN_SLIDES,
    CANNOT_MOVE_BETWEEN_PRESENTATIONS
}
